### ISSUE TITLE
Unhandled 'error' event / Error: getaddrinfo -3008

### ISSUE THREAD

**Issue by johnjohndoe** [derhuerst/fasp-client-cli#2]
I successfully started `fasp-server` on Ubuntu but when I scan for it with `fasp-client` it fails as follows:

``` bash
$ ./node_modules/.bin/fasp-client --scan
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported 
    (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/tmp/foobar/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/tmp/foobar/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/tmp/foobar/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
```

**Comment by derhuerst** [comment]
I tried to mitigate the issue with `search-fasp-receivers@0.2.1`. If you have `fasp-server-cli` installed locally, as we discussed yesterday, run `npm update --depth 10` and try again.

**Comment by derhuerst** [comment]
For documentary purposes: I think the underlying issue is agnat/node_mdns#130 .

**Comment by johnjohndoe** [comment]
I installed the _fasp-server_ and _fasp-client_ like this tonight:

``` bash
$ cd /tmp
$ mkdir foobar
$ cd foobar
$ npm init --yes
$ npm install fasp-server-cli
$ ./node_modules/.bin/fasp-server init foo 1234
$ npm install fasp-client-cli
$ npm update --depth 10
```

Then I successfully started both:
``` bash
$ ./node_modules/.bin/fasp-server
$ ./node_modules/.bin/fasp-client --scan
```
It let me then select the receiver and shows the shell controls:

```
pause space  ◀︎ h l ▶︎  vol ↑100↓  stop .  seek ← →  queue :
```

Seems like, this time it worked.
Nonetheless, I tried to check if the _fasp-receiver_ module was updated here:
``` bash
$ cat ./node_modules/fasp-server/lib/queue.js node_modules/fasp-receiver/package.json
```
The version of the package is `1.0.0`. Is this what you expect?

**Comment by derhuerst** [comment]
> Seems like, this time it worked.

Yup, looks like it. Can you queue an audio file by pressing `:` and pasting the URL?

> Nonetheless, I tried to check if the *fasp-receiver* module was updated here:

I updated `search-fasp-receivers`. You can check that one using `npm ls | grep search-fasp-receivers`.

**Comment by johnjohndoe** [comment]
Thank you, yes I could start playback of an audio file now. Pressing `:` to enqueue a file was not self-explanatory to me. This might be worth being explained somewhat verbose in the `README.md` or renaming `queue` to `open file` or `load file`.

The lookup of `search-fasp-receivers` confirmed that I have version 0.2.1 installed:

``` bash
$ npm ls | grep search-fasp-receivers   
│ ├─┬ search-fasp-receivers@0.2.1
npm ERR! missing: statuses@~1.4.0, required by send@0.16.2
npm ERR! missing: statuses@~1.4.0, required by finalhandler@1.1.1
```

I think the issue is resolved and can be closed.

**Comment by derhuerst** [comment]
In https://github.com/derhuerst/fasp-client-cli/commit/6086a9e379bbd5bdc806c7046359eaaca3be2001, I have added more info about the command line usage.
